insert into categorie_cat (cat_id, cat_nom) values (1, 'Food - Bakery');
insert into categorie_cat (cat_id, cat_nom) values (2, 'Home');
insert into categorie_cat (cat_id, cat_nom) values (3, 'Outdoor');
insert into categorie_cat (cat_id, cat_nom) values (4, 'Pets');
insert into categorie_cat (cat_id, cat_nom) values (5, 'Food - Baking');
insert into categorie_cat (cat_id, cat_nom) values (6, 'Kitchen');
insert into categorie_cat (cat_id, cat_nom) values (7, 'Phone');
insert into categorie_cat (cat_id, cat_nom) values (8, 'Pets');
insert into categorie_cat (cat_id, cat_nom) values (9, 'Tools');
insert into categorie_cat (cat_id, cat_nom) values (10, 'Food - Baked Goods');
insert into categorie_cat (cat_id, cat_nom) values (11, 'Beauty');
insert into categorie_cat (cat_id, cat_nom) values (12, 'Kitchen');
insert into categorie_cat (cat_id, cat_nom) values (13, 'Food - Confectionery');
insert into categorie_cat (cat_id, cat_nom) values (14, 'Accessories');
insert into categorie_cat (cat_id, cat_nom) values (15, 'Outdoor');
insert into categorie_cat (cat_id, cat_nom) values (16, 'Electronics');
insert into categorie_cat (cat_id, cat_nom) values (17, 'Food - Spices');
insert into categorie_cat (cat_id, cat_nom) values (18, 'Food - Health Foods');
insert into categorie_cat (cat_id, cat_nom) values (19, 'Food - Produce');
insert into categorie_cat (cat_id, cat_nom) values (20, 'Food - Snacks');
insert into categorie_cat (cat_id, cat_nom) values (21, 'Home Appliances');
insert into categorie_cat (cat_id, cat_nom) values (22, 'Audio');
insert into categorie_cat (cat_id, cat_nom) values (23, 'Audio');
insert into categorie_cat (cat_id, cat_nom) values (24, 'Pets');
insert into categorie_cat (cat_id, cat_nom) values (25, 'Food - Dairy');
insert into categorie_cat (cat_id, cat_nom) values (26, 'Accessories');
insert into categorie_cat (cat_id, cat_nom) values (27, 'Food - Baking & Cooking');
insert into categorie_cat (cat_id, cat_nom) values (28, 'Food - Dairy');
insert into categorie_cat (cat_id, cat_nom) values (29, 'Food - Condiments');
insert into categorie_cat (cat_id, cat_nom) values (30, 'Outdoor');
insert into categorie_cat (cat_id, cat_nom) values (31, 'Clothing - Skirts');
insert into categorie_cat (cat_id, cat_nom) values (32, 'Tablet');
insert into categorie_cat (cat_id, cat_nom) values (33, 'Outdoor');
insert into categorie_cat (cat_id, cat_nom) values (34, 'Electronics');
insert into categorie_cat (cat_id, cat_nom) values (35, 'Food - Condiments');
insert into categorie_cat (cat_id, cat_nom) values (36, 'Toys');
insert into categorie_cat (cat_id, cat_nom) values (37, 'Monitor');
insert into categorie_cat (cat_id, cat_nom) values (38, 'Food - Meat');
insert into categorie_cat (cat_id, cat_nom) values (39, 'Kitchen');
insert into categorie_cat (cat_id, cat_nom) values (40, 'Food - Beverages');
insert into categorie_cat (cat_id, cat_nom) values (41, 'Beauty');
insert into categorie_cat (cat_id, cat_nom) values (42, 'Outdoor');
insert into categorie_cat (cat_id, cat_nom) values (43, 'Food - Condiments');
insert into categorie_cat (cat_id, cat_nom) values (44, 'Gaming');
insert into categorie_cat (cat_id, cat_nom) values (45, 'Outdoor');
insert into categorie_cat (cat_id, cat_nom) values (46, 'Kitchen');
insert into categorie_cat (cat_id, cat_nom) values (47, 'Food - Produce');
insert into categorie_cat (cat_id, cat_nom) values (48, 'Food - Frozen Food');
insert into categorie_cat (cat_id, cat_nom) values (49, 'Clothing - Bottoms');
insert into categorie_cat (cat_id, cat_nom) values (50, 'Food - Condiments');
insert into categorie_cat (cat_id, cat_nom) values (51, 'Travel');
insert into categorie_cat (cat_id, cat_nom) values (52, 'Clothing - Coats');
insert into categorie_cat (cat_id, cat_nom) values (53, 'Kitchen');
insert into categorie_cat (cat_id, cat_nom) values (54, 'Accessories');
insert into categorie_cat (cat_id, cat_nom) values (55, 'Food - Condiments');
insert into categorie_cat (cat_id, cat_nom) values (56, 'Food - Frozen Foods');
insert into categorie_cat (cat_id, cat_nom) values (57, 'Food - Produce');
insert into categorie_cat (cat_id, cat_nom) values (58, 'Food - Condiments');
insert into categorie_cat (cat_id, cat_nom) values (59, 'Food - Sauces');
insert into categorie_cat (cat_id, cat_nom) values (60, 'Garden');
insert into categorie_cat (cat_id, cat_nom) values (61, 'Food - Snacks');
insert into categorie_cat (cat_id, cat_nom) values (62, 'Office');
insert into categorie_cat (cat_id, cat_nom) values (63, 'Travel');
insert into categorie_cat (cat_id, cat_nom) values (64, 'Health');
insert into categorie_cat (cat_id, cat_nom) values (65, 'Food - Baking');
insert into categorie_cat (cat_id, cat_nom) values (66, 'Sports');
insert into categorie_cat (cat_id, cat_nom) values (67, 'Home');
insert into categorie_cat (cat_id, cat_nom) values (68, 'Outdoor');
insert into categorie_cat (cat_id, cat_nom) values (69, 'Kitchen');
insert into categorie_cat (cat_id, cat_nom) values (70, 'Food - Seafood');
insert into categorie_cat (cat_id, cat_nom) values (71, 'Automotive');
insert into categorie_cat (cat_id, cat_nom) values (72, 'Bicycles');
insert into categorie_cat (cat_id, cat_nom) values (73, 'Food - Frozen Meals');
insert into categorie_cat (cat_id, cat_nom) values (74, 'Food - Canned Goods');
insert into categorie_cat (cat_id, cat_nom) values (75, 'Food - Snacks');
insert into categorie_cat (cat_id, cat_nom) values (76, 'Kitchen');
insert into categorie_cat (cat_id, cat_nom) values (77, 'Toys');
insert into categorie_cat (cat_id, cat_nom) values (78, 'Outdoor');
insert into categorie_cat (cat_id, cat_nom) values (79, 'Food - Baking');
insert into categorie_cat (cat_id, cat_nom) values (80, 'Garden');
insert into categorie_cat (cat_id, cat_nom) values (81, 'Food - Baking');
insert into categorie_cat (cat_id, cat_nom) values (82, 'Food - Soups');
insert into categorie_cat (cat_id, cat_nom) values (83, 'Clothing - Tops');
insert into categorie_cat (cat_id, cat_nom) values (84, 'Food - Frozen Food');
insert into categorie_cat (cat_id, cat_nom) values (85, 'Garden');
insert into categorie_cat (cat_id, cat_nom) values (86, 'Food - Condiments');
insert into categorie_cat (cat_id, cat_nom) values (87, 'Home');
insert into categorie_cat (cat_id, cat_nom) values (88, 'Food - Spices');
insert into categorie_cat (cat_id, cat_nom) values (89, 'Electronics');
insert into categorie_cat (cat_id, cat_nom) values (90, 'Pets');
insert into categorie_cat (cat_id, cat_nom) values (91, 'Food - Snacks');
insert into categorie_cat (cat_id, cat_nom) values (92, 'Pets');
insert into categorie_cat (cat_id, cat_nom) values (93, 'Health');
insert into categorie_cat (cat_id, cat_nom) values (94, 'Food - Bakery');
insert into categorie_cat (cat_id, cat_nom) values (95, 'Food - Frozen Food');
insert into categorie_cat (cat_id, cat_nom) values (96, 'Accessories');
insert into categorie_cat (cat_id, cat_nom) values (97, 'Food - Bakery');
insert into categorie_cat (cat_id, cat_nom) values (98, 'Audio');
insert into categorie_cat (cat_id, cat_nom) values (99, 'Computer');
insert into categorie_cat (cat_id, cat_nom) values (100, 'Food - Snacks');
